### ISSUE TITLE
Script 3-deploy-rancher-on-k3s.sh failed (ncompatible with Kubernetes v1.20.2) #10

### ISSUE THREAD

**Issue by arashkaffamanesh** [kubernauts/bonsai#2]
https://github.com/arashkaffamanesh/bonsai/issues/10

**Comment by alex77g** [comment]
on hold, because official rancher helm chart is restricted to kubeVersion < 1.20.0-0

**Comment by arashkaffamanesh** [comment]
A temporary workaround might be to set v1.19.3+k3s1 version to:

K3S_VERSION=v1.19.3+k3s1

in:

https://github.com/kubernauts/bonsai/blob/master/2-deploy-k3s.sh

**Comment by alex77g** [comment]
should be fixed here #6 by adding a k8s version option
